### ISSUE TITLE
Team Import Error

### ISSUE THREAD

**Issue by nvogen** [nielsenmarkus11/NCAAcalcutta#2]
I get this error when I run
`teams <- import_teams(system.file("extdata", "ncaa-teams-2019.csv", package = "NCAAcalcutta"))`

> Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
 

>  Show Traceback
 
 > Rerun with Debug
 Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input

**Comment by nvogen** [comment]
The 2019 .csv isn't in "C:\Users\...\Documents\R\win-library\3.4\NCAAcalcutta\extdata"

When I manually copied it in there, it worked.

**Comment by nielsenmarkus11** [comment]
@nvogen, did this resolve when you installed the newer version of the package?  Thanks.
