### ISSUE TITLE
Region not outputted

### ISSUE THREAD

**Issue by nvogen** [nielsenmarkus11/NCAAcalcutta#3]
Looks like you overwrite region with opponent

`output$region <- renderText({
        input$nextteam
        input$lastteam
        # tmp <- curr.row()
        paste0("Region: ",
               teams$region[i]
               # as.character(tmp$region)
        )
      })`
      
      `output$region <- renderText({
        input$nextteam
        input$lastteam
        # tmp <- curr.row()
        paste0("Opponent: ",
               teams$opponent[i]
               # as.character(tmp$region)
        )
      })`

**Comment by nielsenmarkus11** [comment]
Thanks @nvogen. I've merged your pull request https://github.com/nielsenmarkus11/NCAAcalcutta/pull/4
